checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
          - magento/framework

build:
    environment:
        php:
            version: 7.0.8
        postgresql: false
        mongodb: false

    tests:
        override:
            - vendor/bin/phpunit
            -
                command: 'vendor/bin/phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
        stop_on_failure: false
        override:
            - phpcs-run --standard=./vendor/magento-ecg/coding-standard/EcgM2/ruleset.xml /
            - phpcs-run --standard=./vendor/magento/marketplace-eqp/MEQP2/ruleset.xml /
