checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
          - magento/framework

build:
    environment:
        php:
            version: 7.0.8
        postgresql: false
        mongodb: false

    tests:
        stop_on_failure: false
        override:
            - phpcs-run --ignore=*/vendor/* --standard=./vendor/magento-ecg/coding-standard/EcgM2/ruleset.xml /home/scrutinizer/build
tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ vendor/* ]

  php_analyzer:
    filter:
      excluded-paths: [ vendor/* ]
